name: Test Java 8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
        matrix:
          jdk: [ '8', '11' ]
          os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    continue-on-error: true 
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -P\!build-android -nsu -B -Pjacoco install
